# Assignment #9 - Data Gathering and Warehousing - DSSA-5102

Instructor: Melissa Laurino</br>
Spring 2025</br>

Name: Madison Souder
</br>
Date: April 24, 2025
<br>
<br>
**At this time in the semester:** <br>
- We have explored a dataset. <br>
- We have cleaned our dataset. <br>
- We created a Github account with a repository for this class and included a metadata read me file about our data. <br>
- We introduced general SQL syntax, queries, and applications in Python.<br>
- Created our own databases from scratch using MySQL Workbench and Python with SQLAlchemy on our local server and locally on our machine.
- Populated our databases with the data we cleaned at the start of the semester.
<br>

At this point, we have discussed all major statements used with SQL, but the possibilities are endless when it comes to data! Below we will explore some miscellaneous statements and tools that may be useful with your database.<br>

<br>

Read Chapter 7 & 10 in Getting Started with SQL by Thomas Nield available on Blackboard. <br>
A quick reference for SQL commands: https://www.w3schools.com/sql/default.asp <br>

Review the powerpoint and other readings specified on Blackboard in the Discussion Board.<br>

In the event your database does not meet the requirements below to answer the question, please use the database provided in Assignment #4 and #5. Remember to credit your data source, especially when posting your assignments to Github.<br>

Feel free to use your preferred library and method for the exploration below. Now that all of our data is loaded onto the MySQL Workbench server, you can even take the assignment a step further and complete it all within SQL without Jupyter Notebook!<br>

Follow the instructions below to complete the assignment. Be sure to comment **all** code and answer **all** questions in markdown for full credit. Please submit this assignment with a link to it posted to your Github.<br>

**Data origin:** US Chronic Disease Indicators Database

In [1]:
# Load necessary packages:
from sqlalchemy import create_engine, Column, String, Integer, Boolean, BigInteger, Float, text # Database navigation
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import mysql.connector
import sqlite3 # A second option for working with databases
import pandas as pd # Python data manilpulation
import numpy as np # Populating our tables

In [2]:
# Connect to the MySQL server 

conn = mysql.connector.connect(
        host = "localhost", # This is your local instance number when you open MySQL Workbench.
        user = "root", # This is your username for MySQL Workbench
        password = "Graduate!2025") # We wrote this password down in our first class!

cursor = conn.cursor()

# Since my database is created now, I USE The database instead.
cursor.execute("USE chronic_disease_indicators")
print("Using the chronic_disease_indicators!")

Using the chronic_disease_indicators!

In [3]:
# Time to connect to the database using SQL Alchemy by creating an engine:
DATABASE_URL = "mysql+mysqlconnector://root:Graduate!2025@localhost/chronic_disease_indicators" # Use MySQL Connector to connect to the database
engine = create_engine(DATABASE_URL) # Creates a connection to the MySQL database

print("Connected to MySQL database successfully!")

Connected to MySQL database successfully!

In [4]:
# Write a query to list the table names of the database:
with engine.connect() as connection: #Creates the connection
    query = text("""SELECT table_name
                    FROM information_schema.tables
                    WHERE table_schema = 'chronic_disease_indicators'
                    AND table_type = 'BASE TABLE';""") #Selects table_name from my tables information_schema 
                                                       #Where the table_schema equals chronic_disease_indicators and the table_type equals base table
    table_names = pd.read_sql(query, connection) #Reads the query with connection to the database

table_names #Prints the results

                                       TABLE_NAME
0                                         alcohol
1                                       arthritis
2                                          asthma
3                                          cancer
4                          cardiovascular_disease
5                          chronic_kidney_disease
6           chronic_obstructive_pulmonary_disease
7                 cognitive_health_and_caregiving
8                                        diabetes
9                                      disability
10                                  health_status
11                                   immunization
12                                maternal_health
13                                  mental_health
14  nutrition_physical_activity_and_weight_status
15                                    oral_health
16                                          sleep
17                  social_determinants_of_health
18                                        tobacco
19                                         topics

#### CASE Statements
Case statements are similar to the if-then-else statements in programming. The data that meets the case statements in the database will be returned. You start a CASE statement with the word CASE and conclude it with an END. Between those keywords, you specify each condition with a WHEN [condition] THEN [value], where the condition and the values are specified by you.

Nield, Thomas. Getting Started with SQL (p. 71). O'Reilly Media. Kindle Edition. <br>
<br>
Write your question you are answering with your data query. <br>
<br>
**Example Question:** What US state, territory, or district collects the most data about obesity in adults?
<br>
**What tables are we joining? (If any):** topics and nutrition_physical_activity_and_weight_status

In [5]:
#Left JOIN and Case Query 1
with engine.connect() as connection: #Creates the connection
    join_query = text("""SELECT t.location_desc AS location,
                         COUNT(npa.question) AS data_collection_frequency,
                         CASE
                                 WHEN COUNT(npa.question) >= 30 THEN 'Most concerned'
                                 WHEN COUNT(npa.question) = 0 THEN 'Not concerned'
                                 ELSE 'Some concern'
                            END AS concern
                        FROM topics t
                        LEFT JOIN nutrition_physical_activity_and_weight_status npa 
                            ON t.topic_id = npa.nutrition_physical_activity_and_weight_status_id
                            AND npa.question = 'Obesity among adults'
                        WHERE t.topic = 'Nutrition, Physical Activity, and Weight Status'
                        GROUP BY t.location_desc
                        ORDER BY data_collection_frequency DESC""")
                        #Selects the location_desc from the topics table 
                        #Counts the question frequency from the nutrition_physical_activity_and_weight_status table
                        #When the count is greater than 30, the location is labeled most concerned,
                        #When the count is equal to 0, then the location is labeled not concerned,
                        #When the count is anything else, the location is labeled as some concern.
                        #The tables are left joined by the topic_id and the nutrition_physical_activity_and_weight_status_id
                        #And the question must equal 'Obesity among adults'
                        #Where the topic equals 'Nutrition, Physical Activity, and Weight Status'
                        #Grouped by the location_desc and ordered by the COUNT in descending order
    join_query = pd.read_sql(join_query, connection) #Reads the query with connection to the databse

join_query #Prints the results

                location  data_collection_frequency         concern
0                Arizona                         43  Most concerned
1               Arkansas                         40  Most concerned
2                 Alaska                         39  Most concerned
3                Alabama                         37  Most concerned
4          United States                          6    Some concern
5               Missouri                          3    Some concern
6               Illinois                          3    Some concern
7                 Nevada                          3    Some concern
8            Connecticut                          3    Some concern
9                Georgia                          2    Some concern
10                Oregon                          2    Some concern
11          South Dakota                          2    Some concern
12                 Maine                          2    Some concern
13             Tennessee                          2    Some concern
14               Montana                          2    Some concern
15              Maryland                          2    Some concern
16              Colorado                          1    Some concern
17        North Carolina                          1    Some concern
18            California                          1    Some concern
19               Indiana                          1    Some concern
20           Mississippi                          1    Some concern
21            New Mexico                          1    Some concern
22                Hawaii                          1    Some concern
23               Florida                          1    Some concern
24             Wisconsin                          1    Some concern
25          Pennsylvania                          1    Some concern
26                  Utah                          1    Some concern
27         Massachusetts                          1    Some concern
28               Wyoming                          1    Some concern
29          North Dakota                          1    Some concern
30                 Idaho                          1    Some concern
31            Washington                          1    Some concern
32             Louisiana                          1    Some concern
33              Virginia                          1    Some concern
34            New Jersey                          1    Some concern
35              Delaware                          1    Some concern
36         New Hampshire                          1    Some concern
37              New York                          0   Not concerned
38                  Ohio                          0   Not concerned
39             Minnesota                          0   Not concerned
40  District of Columbia                          0   Not concerned
41          Rhode Island                          0   Not concerned
42         West Virginia                          0   Not concerned
43                Kansas                          0   Not concerned
44              Oklahoma                          0   Not concerned
45                 Texas                          0   Not concerned
46               Vermont                          0   Not concerned
47                  Iowa                          0   Not concerned
48              Kentucky                          0   Not concerned
49              Michigan                          0   Not concerned
50        South Carolina                          0   Not concerned
51              Nebraska                          0   Not concerned
52                  Guam                          0   Not concerned
53           Puerto Rico                          0   Not concerned
54        Virgin Islands                          0   Not concerned

**CASE STATEMENT**
<br>
Write a second CASE statement!

Write your question you are answering with your data query. <br>
<br>
**Question:** Which chronic disease topics have the most available public information?
<br>
**What tables are we joining? (If any):** None

In [6]:
#Case Query 2
with engine.connect() as connection: #Creates the connection
    case_query = text("""SELECT topic,
                         COUNT(*) AS available_information,
                         CASE
                                 WHEN COUNT(*) >= 10000 THEN 'Most Research'
                                 WHEN COUNT(*) >= 5000 THEN 'Good Amount of Research'
                                 WHEN COUNT(*) >= 1000 THEN 'Okay Amount of Research'
                                 WHEN COUNT(*) < 1000 THEN 'More Research Needed'
                             END AS research
                         FROM topics
                         GROUP BY topic
                         ORDER BY available_information desc""")
                         #Selects the topic from the topics tables and counts their frequency
                         #When the count is greater than or equal to 10,000, then the topic is labeled as 'Most Research'
                         #When the count is greater than or equal to 5,000, then the topic is labeled as 'Good Amount of Research'
                         #When the count is greater than or equal to 1,000, then the topic is labeled as 'Okay Amount of Research'
                         #When the count is less than 1,000, then the topic is labeled as 'More Research Needed'
                         #Grouped by the topics and ordered by the count in descending order
    case_query = pd.read_sql(case_query, connection) #Reads the query with connection to the database

case_query #Prints the results

,topic,available_information,research
0,Cardiovascular Disease,23393,Most Research
1,"Nutrition, Physical Activity, and Weight Status",19618,Most Research
2,Health Status,19157,Most Research
3,Chronic Obstructive Pulmonary Disease,18337,Most Research
4,Cancer,16499,Most Research
5,Alcohol,16398,Most Research
6,Social Determinants of Health,12307,Most Research
7,Immunization,12242,Most Research
8,Arthritis,11960,Most Research
9,Mental Health,11732,Most Research
10,Diabetes,11043,Most Research
11,Tobacco,9580,Good Amount of Research
12,Oral Health,9030,Good Amount of Research
13,Asthma,5231,Good Amount of Research
14,Sleep,4152,Okay Amount of Research
15,Disability,4029,Okay Amount of Research
16,Cognitive Health and Caregiving,3782,Okay Amount of Research
17,Maternal Health,602,More Research Needed
18,Chronic Kidney Disease,104,More Research Needed

**CASE STATEMENT**
<br>
Write a third CASE statement!

Write your question you are answering with your data query. <br>
<br>
**Question:** What questions are most frequently asked when talking about cardiovascular disease?
<br>
**What tables are we joining? (If any):** None

In [7]:
#Case Query 3
with engine.connect() as connection: #Creates the connection
    case_query_3 = text("""SELECT question,
                         COUNT(*) as frequency_count,
                         CASE
                                 WHEN COUNT(*) >= 4000 THEN 'Most Popular'
                                 WHEN COUNT(*) >= 2000 THEN 'Popular'
                                 WHEN COUNT(*) >= 1000 THEN 'Least Popular'
                             END AS popularity
                         FROM cardiovascular_disease
                         GROUP BY question
                         ORDER BY COUNT(*) desc""")
                         #Selects the question from the cardiovascular_disease table and counts their frequency
                         #When the count is greater than or equal to 4,000, then the question is labeled as 'Most Popular'
                         #When the count is greater than or equal to 2,000, then the question is labeled as 'Popular'
                         #When the count is greater than or equal to 1,000, then the question is labeled as 'Least Popular'
                         #Grouped by the question and ordered by the count in descending order
    case_query_3 = pd.read_sql(case_query_3, connection) #Reads the query with connection to the database

case_query_3 #Prints the results

,question,frequency_count,popularity
0,Diseases of the heart mortality among all peop...,4570,Most Popular
1,Coronary heart disease mortality among all peo...,4222,Most Popular
2,Cerebrovascular disease (stroke) mortality amo...,3897,Popular
3,Hospitalization for heart failure as principal...,3195,Popular
4,Taking medicine for high cholesterol among adults,1965,Least Popular
5,High cholesterol among adults who have been sc...,1963,Least Popular
6,High blood pressure among adults,1916,Least Popular
7,Taking medicine to control high blood pressure...,1665,Least Popular

**NULL**
<br>
As with all data, NULL values are fields with no data. Null data can be useful to know with the INSERT INTO statement below.

Find the NULL data within your database. Write your question you are answering with your data query. <br>
<br>
**Question:** Selecting all the entries from the cardiovascular_disease table where the data_value column is null
<br>

In [8]:
#NULL Query
with engine.connect() as connection: #Creates the connection
    null_query = text("""SELECT *
                         FROM cardiovascular_disease
                         WHERE data_value IS NULL""") #Selects all entries from the cardiovascular_disease table there the data_value column in NULL
    null_query = pd.read_sql(null_query, connection) #Reads the query with connection to the database

null_query #Prints the results

#Prior to creating the database, I cleaned the data extensively and the database does not have any null values.

Empty DataFrame
Columns: [cardiovascular_disease_id, question, data_value, data_value_unit, data_value_type, stratification_category_1, stratification_1]
Index: []

**INSERT INTO**
<br>
You can insert new records into a table as needed using the INSERT INTO statement. If you choose to populate a table with certain records and not others, the rest of the fields will remain empty/NULL.
<br>
For INSERT INTO, we are not querying the database, instead we are ADDING to it. We do not need to use dbGetQuery(), but instead, dbExecute()!
<br><br>
**Objective:** Manually insert new data entries into the topics table
<br>
**What table(s) are we adding a record to?** topics

In [ ]:
#INSERT INTO Query
# with engine.connect() as connection: #Creates the connection
   # connection.execute(text("""INSERT INTO topics (topic, data_source, location_desc, year_start, year_end)
                              # VALUES ('Chronic Kidney Disease', 'USRDS', 'New Jersey', '2023', '2023'),
                              #        ('Maternal Health', 'PRAMS', 'United States', '2020', '2021'),
                              #        ('Disability', 'BRFSS', 'California', '2020', '2022');"""))

#Becauase I do not want to actually insert new rows into the topics tables, I commented out my code. I made up this data and do not need it in my data.

**MIN() and MAX()**
<br>
You can use these statements alone or in combination with the CASE statemts above.<br>
The IN operator in a WHERE clause lets you filter for multiple values at once. You can also exclude certain values by using the NOT IN operator.
<br>

**Question:** What is the minimum and maximum start year for the research topics diabetes and alcohol?
<br>
**What table(s) are we joining? (If any):** None

In [9]:
#MIN and MAX Query
with engine.connect() as connection: #Creates the connection
    query = text("""SELECT topic,
                    MIN(year_start) AS minimum_start_year,
                    MAX(year_start) AS maximum_start_year
                    FROM topics 
                    WHERE topic IN ('Diabetes', 'Alcohol')
                    GROUP BY topic
                    ORDER BY minimum_start_year""")
                    #Selects the topic from the topics table and finds the minimum start year and the maximum start year
                    #Where the topic equals diabetes or alcohol, groups by the topic and orders the results by the minimum start year
    min_max_query = pd.read_sql(query, connection) #Reads the query with connection to the database

min_max_query #Prints the results

      topic  minimum_start_year  maximum_start_year
0  Diabetes                2019                2022
1   Alcohol                2019                2022

Combine CASE statement with Min() and Max() for a more detailed query of your data:
<br><br>
**Question:** What location has the largest range in age-adjusted prevalence in binge drinking among adults across all years?
<br>
**What table(s) are we joining?:** Topics and Alcohol

In [10]:
#MIN and MAX with CASE Query
with engine.connect() as connection: #Creates the connection
    query = text("""SELECT t.location_desc,
                    MAX(a.data_value) AS highest_prevalence,
                    MIN(a.data_value) AS lowest_prevalence,
                    MAX(a.data_value) - MIN(a.data_value) AS prevalence_range,
                    CASE
                           WHEN MAX(a.data_value) - MIN(a.data_value) >= 20 THEN 'Biggest range'
                           WHEN MAX(a.data_value) - MIN(a.data_value) < 20 THEN 'Smallest range'
                        END AS range_category
                    FROM topics t
                    JOIN alcohol a ON t.topic_id = a.alcohol_id
                    WHERE question = 'Binge drinking prevalence among adults'
                    AND data_value_type = 'Age-adjusted Prevalence'
                    GROUP BY location_desc
                    ORDER BY prevalence_range DESC""")
                    #Selects the location from the topics table
                    #Pulls the max data value and the min data value from the alcohol table, calculates the range by subtracting the min from the max
                    #When the range is greater than or equal to 20, then the location is labeled 'Biggest range'
                    #When the range is less than 20, then the location is labeled 'Smallest range'
                    #INNER JOINs the topics and alcohol table by topic_id and alcohol_id
                    #Where the question is 'Binge drinking prevalence among adults'
                    #And the data_value_tyoe is 'Age-adjusted Prevalence'
                    #Groups by the location and orders by the range
    min_max_case = pd.read_sql(query, connection) #Reads the query with connection to the database
    
min_max_case #Prints the results

,location_desc,highest_prevalence,lowest_prevalence,prevalence_range,range_category
0,Nebraska,43,10,33,Biggest range
1,New York,30,0,30,Biggest range
2,United States,41,11,30,Biggest range
3,South Carolina,35,6,29,Biggest range
4,Missouri,34,7,27,Biggest range
5,Nevada,34,8,26,Biggest range
6,North Carolina,30,4,26,Biggest range
7,Oregon,36,11,25,Biggest range
8,New Hampshire,35,10,25,Biggest range
9,Utah,32,9,23,Biggest range
10,Oklahoma,35,12,23,Biggest range
11,Idaho,30,8,22,Biggest range
12,Indiana,31,9,22,Biggest range
13,Kentucky,29,8,21,Biggest range
14,Texas,31,10,21,Biggest range
15,Michigan,29,8,21,Biggest range
16,Washington,30,9,21,Biggest range
17,Iowa,31,10,21,Biggest range
18,Rhode Island,28,7,21,Biggest range
19,West Virginia,28,8,20,Biggest range
20,Alaska,30,10,20,Biggest range
21,New Mexico,29,9,20,Biggest range
22,Maine,29,9,20,Biggest range
23,Kansas,27,8,19,Smallest range
24,Louisiana,30,11,19,Smallest range
25,Tennessee,27,8,19,Smallest range
26,Mississippi,27,8,19,Smallest range
27,South Dakota,25,6,19,Smallest range
28,Ohio,26,7,19,Smallest range
29,California,29,10,19,Smallest range
30,Alabama,25,7,18,Smallest range
31,Virginia,27,9,18,Smallest range
32,Vermont,27,9,18,Smallest range
33,Arkansas,24,6,18,Smallest range
34,Colorado,29,11,18,Smallest range
35,Montana,26,8,18,Smallest range
36,Arizona,27,10,17,Smallest range
37,Minnesota,28,11,17,Smallest range
38,Georgia,25,8,17,Smallest range
39,Florida,24,8,16,Smallest range
40,Pennsylvania,23,7,16,Smallest range
41,Connecticut,24,9,15,Smallest range
42,Wisconsin,25,10,15,Smallest range
43,Delaware,23,8,15,Smallest range
44,District of Columbia,23,9,14,Smallest range
45,New Jersey,24,10,14,Smallest range
46,North Dakota,22,8,14,Smallest range
47,Massachusetts,24,10,14,Smallest range
48,Illinois,25,12,13,Smallest range
49,Maryland,24,11,13,Smallest range
50,Hawaii,24,11,13,Smallest range
51,Wyoming,21,9,12,Smallest range
52,Puerto Rico,19,15,4,Smallest range

**MIN() and MAX()** <br>
AVG() will take the average of a numeric field.

**Question:** Building on the last question, what location has the highest average age-adjusted binge drinking prevalence among adults, and what location has the lowest average?
<br>
**What table(s) are we joining?:** Topics and Alcohol

In [11]:
with engine.connect() as connection: #Creates the connection
    query = text("""SELECT t.location_desc,
                    AVG(a.data_value)
                    FROM topics t
                    JOIN alcohol a ON t.topic_id = a.alcohol_id
                    WHERE question = 'Binge drinking prevalence among adults'
                    AND data_value_type = 'Age-adjusted Prevalence'
                    GROUP BY location_desc
                    ORDER BY AVG(a.data_value) DESC""")
                    #Selects the location_desc from the topics table and finds the average data_value from the alcohol table
                    #INNER JOINs the alcohol table and topics table by the topic_id and alcohol_id
                    #Where the question is 'Binge drinking prevalence among adults'
                    #And the data_value type is 'Age-adjusted Prevalence'
                    #Groups by the location and orders by the average in descending order
    avg = pd.read_sql(query, connection) #Reads the query with connection to the database
    
avg #Prints the results

           location_desc  AVG(a.data_value)
0          New Hampshire            19.2353
1               Oklahoma            19.0000
2                 Oregon            18.9394
3                Indiana            18.8919
4              Minnesota            18.7083
5                   Utah            18.5625
6               Illinois            18.5333
7          United States            18.4722
8         South Carolina            18.1429
9                 Hawaii            18.0000
10              Michigan            17.8929
11               Alabama            17.8718
12             Tennessee            17.8261
13               Arizona            17.8113
14              Kentucky            17.7600
15             Wisconsin            17.7586
16              Nebraska            17.7143
17               Vermont            17.7037
18            Washington            17.5517
19                 Idaho            17.4800
20         West Virginia            17.4783
21                  Iowa            17.4516
22           Mississippi            17.4400
23              Missouri            17.3714
24        North Carolina            17.2059
25  District of Columbia            17.1905
26              Maryland            17.1250
27              Virginia            17.0303
28                Nevada            17.0286
29           Puerto Rico            17.0000
30            New Jersey            16.9545
31             Louisiana            16.8846
32                Kansas            16.8485
33            California            16.8462
34          Pennsylvania            16.8148
35               Montana            16.8077
36                 Texas            16.7941
37          Rhode Island            16.7241
38                Alaska            16.7073
39              Arkansas            16.6739
40              Colorado            16.6471
41            New Mexico            16.6333
42                  Ohio            16.5926
43           Connecticut            16.5769
44                 Maine            16.5000
45               Florida            16.5000
46          South Dakota            16.2500
47         Massachusetts            16.1538
48               Georgia            15.9688
49              New York            15.9167
50               Wyoming            15.6250
51              Delaware            15.2500
52          North Dakota            14.5333

**Aliases (AS)**
<br>
You can abbreviate your code to make it more visually appealing...or more confusing? :) <br>
<br>
Examples:<br>
FROM table_name t<br>
FROM table_name AS t<br>
<br>
**Objective:** Use abbreviations or aliases for all tables for the same code you wrote above (If you have not done so already). Be sure to obtain the same result set.

In [12]:
with engine.connect() as connection: #Creates the connection
    query = text("""SELECT t.location_desc AS location,
                    AVG(a.data_value) AS average_binge_drinking_prevalence_among_adults
                    FROM topics t
                    JOIN alcohol a ON t.topic_id = a.alcohol_id
                    WHERE question = 'Binge drinking prevalence among adults'
                    AND data_value_type = 'Age-adjusted Prevalence'
                    GROUP BY location
                    ORDER BY average_binge_drinking_prevalence_among_adults DESC""")
                    #Selects the location_desc from the topics table and finds the average data_value from the alcohol table
                    #INNER JOINs the alcohol table and topics table by the topic_id and alcohol_id
                    #Where the question is 'Binge drinking prevalence among adults'
                    #And the data_value type is 'Age-adjusted Prevalence'
                    #Groups by the location and orders by the average in descending order
    avg_2 = pd.read_sql(query, connection) #Reads the query with connection to the database
    
avg_2 #Prints the results

#This is the same code I used in the average query, but I used more abbreviations and aliases.

                location  average_binge_drinking_prevalence_among_adults
0          New Hampshire                                         19.2353
1               Oklahoma                                         19.0000
2                 Oregon                                         18.9394
3                Indiana                                         18.8919
4              Minnesota                                         18.7083
5                   Utah                                         18.5625
6               Illinois                                         18.5333
7          United States                                         18.4722
8         South Carolina                                         18.1429
9                 Hawaii                                         18.0000
10              Michigan                                         17.8929
11               Alabama                                         17.8718
12             Tennessee                                         17.8261
13               Arizona                                         17.8113
14              Kentucky                                         17.7600
15             Wisconsin                                         17.7586
16              Nebraska                                         17.7143
17               Vermont                                         17.7037
18            Washington                                         17.5517
19                 Idaho                                         17.4800
20         West Virginia                                         17.4783
21                  Iowa                                         17.4516
22           Mississippi                                         17.4400
23              Missouri                                         17.3714
24        North Carolina                                         17.2059
25  District of Columbia                                         17.1905
26              Maryland                                         17.1250
27              Virginia                                         17.0303
28                Nevada                                         17.0286
29           Puerto Rico                                         17.0000
30            New Jersey                                         16.9545
31             Louisiana                                         16.8846
32                Kansas                                         16.8485
33            California                                         16.8462
34          Pennsylvania                                         16.8148
35               Montana                                         16.8077
36                 Texas                                         16.7941
37          Rhode Island                                         16.7241
38                Alaska                                         16.7073
39              Arkansas                                         16.6739
40              Colorado                                         16.6471
41            New Mexico                                         16.6333
42                  Ohio                                         16.5926
43           Connecticut                                         16.5769
44                 Maine                                         16.5000
45               Florida                                         16.5000
46          South Dakota                                         16.2500
47         Massachusetts                                         16.1538
48               Georgia                                         15.9688
49              New York                                         15.9167
50               Wyoming                                         15.6250
51              Delaware                                         15.2500
52          North Dakota                                         14.5333

Now we are starting to create multiple new fields that we can save any time as a .csv if needed to access later. Save your result set as a .csv:

In [13]:
#Save result set as .csv file:
avg_2.to_csv("Avg_binge_drinking_adults.csv", index=False)

**DELETE** ~Caution!~
<br>
You can delete all records from specific tables or set a criteria to delete certain values or NULL values without deleting the table itself. It is okay if you do not execute the code if you have completed all data cleaning steps earlier in the semester.<br>
<br>
If you created autoincrement IDs for any of your data, it is recommended to use TRUNCATE TABLE instead, used the same way. The ID's will automatically reset if needed.<br>
<br>
**Objective:** Delete all data from the topics table where is location_desc is NULL
<br>
**What table(s) are we deleting records from?** topics

In [24]:
#with engine.connect() as connection: #Creates the connection
#    delete = text("""DELETE FROM topics
#                     WHERE location_desc IS NULL""")
#    connection.execute(delete)
#    connection.commit() 

#I do not want to risk deleting any rows so I will not run this.

We can also delete entire tables in MySQL workbench by manually right clicking on the table and DROP TABLE. <br>
MySQL Workbench will prompt you to review the SQL syntax before dropping the table.<br>
The syntax is simple:<br>
DROP TABLE table_name<br>

In [14]:
#Close the database connection :)
connection.close()

**STOP**<br>
Before you submit, did you comment all your code?<br>
Did you answer all of the questions in the markdown cells?<br>
Did you rename the file and write your name at the top of the .pynb?<br>
Attach the .csv file you created with your Blackboard submission. It is preferred that you submit your Github link instead of the file itself.